---
- block:
  - name: kubernetes/cni-calico | mktemp
    command: mktemp -d
    register: _mktemp

  - name: kubernetes/cni-calico | grab the yaml
    get_url:
      url: https://docs.projectcalico.org/v3.7/manifests/calico.yaml
      dest: "{{ _mktemp.stdout }}"

  - name: kubernetes/cni-calico | regex changes
    command: sed -i "s/192.168.0.0\/16/10.0.0.0\/24/g" {{ _mktemp.stdout }}/calico.yaml

  - name: kubernetes/cni-calico | regex changes
    command: sed -i "s/calico\/node:v3.7.2/calico\/node:latest-arm64/g" {{ _mktemp.stdout }}/calico.yaml

  - name: kubernetes/cni-calico | apply
    command: kubectl apply -f {{ _mktemp.stdout }}/calico.yaml

  always:
  - name: kubernetes/cni-calico | cleanup
    file:
      path: "{{ _mktemp.stdout }}"
      state: absent
