#!/bin/bash
# Post kernel install script that will ensure the proper values are set for config.txt and cmdline.txt
#
# Should be placed in /etc/kernel/postinst.d

# Get the new kernel version
kernel_version=$(ls /lib/modules)

echo "Found Kernel version ${kernel_version}"

# Fix config.txt
echo "Updating /boot/config.txt"
sed -i "s/initramfs.*$/initramfs initrd.img-${kernel_version} followkernel/g" /boot/config.txt
