---
- name: kubernetes/pre-reqs | figure out if we are on armbian
  shell: systemctl list-unit-files | grep armbian
  register: _prereqs_armbian
  ignore_errors: yes

- block:
  - name: kubernetes/pre-reqs | disable swap
    command: swapoff -a

  - name: kubernetes/pre-reqs | systemctl stop
    systemd:
      name: '{{ item }}'
      state: stopped
      enabled: no
    with_items:
    - armbian-ramlog
    - armbian-zram-config
  when: _prereqs_armbian.rc == 0

# TODO: Assume Raspian all the time?
- name: kubernetes/pre-reqs | setup iptables legacy mode
  command: '{{ item }}'
  with_items:
  - update-alternatives --set iptables /usr/sbin/iptables-legacy
  - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
  - update-alternatives --set arptables /usr/sbin/arptables-legacy
  - update-alternatives --set ebtables /usr/sbin/ebtables-legacy

- name: kubernetes/pre-reqs | disable swap
  systemd:
    name: dphys-swapfile
    state: stopped
    enabled: no
