---
- block:
  - name: docker | mktemp
    command: mktemp -d
    register: _mktemp

  - name: docker | get gpg key
    copy:
      src: docker_apt_key.gpg
      dest: "{{ _mktemp.stdout }}"

  - name: docker | apply gpg key
    apt_key:
      file: "{{ _mktemp.stdout }}/docker_apt_key.gpg"
      state: present

  always:
  - name: docker | cleanup
    file:
      name: "{{ _mktemp.stdout }}"
      state: absent

# Designed for Raspian at the moment
- name: docker | add apt repo
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable

# install_recommends is set to no because that is what get.docker.com does as of this writing (aufs dkms issue)
- name: docker | install docker-ce
  apt:
    name: '{{ docker_pkgs }}'
    state: present
    state: present
    install_recommends: no

- name: docker | template out daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker

- name: docker | enable systemd
  systemd:
    name: docker
    enabled: yes
    state: started

- name: docker | flush handlers
  meta: flush_handlers
